"""The Aurora draft maps the source data_type first (issue #274)."""

from __future__ import annotations

import json
import zipfile
from pathlib import Path

import pytest

from src.contracts.schema_design_input import AgentTable
from src.tools.schema.aurora_common.ddl_generator import generate_mysql_ddl, generate_pg_ddl

_ROOT = Path(__file__).resolve().parents[5]


def _table(columns, **extra) -> AgentTable:
    return AgentTable.model_validate(
        {"table_id": "db.t", "table_name": "t", "row_count": 1, "columns": columns, **extra}
    )


def _col(name, data_type, normalized=None, **extra) -> dict:
    return {
        "column_name": name,
        "data_type": data_type,
        "normalized_data_type": normalized,
        "nullable": True,
        **extra,
    }


def test_pg_carry_over_uses_the_source_type_when_normalized_is_missing():
    table = _table(
        [
            _col("id", "bigint", nullable=False, is_auto_increment=True),
            _col("n", "integer"),
            _col("name", "character varying", max_length=50),
            _col("tags", "_varchar"),
            _col("at", "timestamp without time zone", "timestamp"),
        ],
        primary_key=["id"],
    )

    result = generate_pg_ddl([table], source_engine="postgresql")

    types = {c.name: c.aurora_type for c in result.tables[0].columns}
    assert types == {
        "id": "BIGINT",
        "n": "INTEGER",
        "name": "VARCHAR(50)",
        "tags": "VARCHAR[]",
        "at": "TIMESTAMP",  # the normalized map would say TIMESTAMPTZ
    }
    assert result.residuals == []
    assert all(c.script_derived and not c.needs_judgment for c in result.tables[0].columns)
    assert '"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL' in result.full_ddl


def test_mysql_carry_over_keeps_unsigned_and_long_text():
    table = _table(
        [
            _col("ID", "bigint unsigned", "integer", nullable=False, is_auto_increment=True),
            _col("post_content", "longtext", "text"),
            _col("menu_order", "int", "integer"),
            _col("ok", "tinyint(1)", "integer"),
            _col("price", "decimal(26,8)", "decimal"),
            _col("status", "enum('draft','publish')", "string"),
        ],
        primary_key=["ID"],
    )

    result = generate_mysql_ddl([table], source_engine="mysql")

    assert result.residuals == []
    assert "`ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL" in result.full_ddl
    assert "`post_content` LONGTEXT" in result.full_ddl
    assert "`menu_order` INT" in result.full_ddl
    assert "`ok` TINYINT(1)" in result.full_ddl
    assert "`price` DECIMAL(26,8)" in result.full_ddl
    assert "`status` ENUM('draft','publish')" in result.full_ddl


def test_cross_engine_pg_to_mysql_and_mysql_to_pg():
    pg_source = _table(
        [_col("id", "integer"), _col("body", "text"), _col("data", "jsonb")], primary_key=["id"]
    )
    my = generate_mysql_ddl([pg_source], source_engine="postgresql")
    assert {c.name: c.aurora_type for c in my.tables[0].columns} == {
        "id": "INT",
        "body": "LONGTEXT",
        "data": "JSON",
    }
    mysql_source = _table(
        [_col("id", "bigint unsigned", "integer"), _col("at", "datetime", "datetime")],
        primary_key=["id"],
    )
    pg = generate_pg_ddl([mysql_source], source_engine="mysql")
    assert {c.name: c.aurora_type for c in pg.tables[0].columns} == {
        "id": "BIGINT",
        "at": "TIMESTAMP",
    }


def test_unmappable_source_type_stays_a_residual_with_its_source_type():
    table = _table([_col("status", "hotlinked_media_status")])

    result = generate_pg_ddl([table], source_engine="postgresql")

    assert [(r["column"], r["source_type"], r["fallback_type"]) for r in result.residuals] == [
        ("status", "hotlinked_media_status", "TEXT")
    ]


def test_other_sources_keep_the_normalized_mapping():
    table = _table([_col("id", "NUMBER(10)", "integer")])
    result = generate_pg_ddl([table], source_engine="oracle")
    assert result.tables[0].columns[0].aurora_type == "BIGINT"


def test_hostile_source_type_never_reaches_ddl():
    table = _table([_col("x", "bigint); DROP TABLE users; --")])
    result = generate_mysql_ddl([table], source_engine="mysql")
    assert "DROP" not in result.full_ddl
    assert result.residuals[0]["column"] == "x"


# ---------------------------------------------------------------------------
# Bundled discourse sample: residuals before / after
# ---------------------------------------------------------------------------


def _sample_tables(name: str) -> list[AgentTable]:
    from src.agents.collector.mysql_collector import _build_tables
    from src.tools.database.offline_parser import parse_offline_collection

    archive = _ROOT / "docs" / "examples" / name / f"{name}.zip"
    with zipfile.ZipFile(archive) as zf:
        content = zf.read(f"{name}-collection.json").decode().strip()
    if not content.startswith("{"):  # mysql client header line ("collection_output")
        content = content[content.index("\n") + 1 :]
    raw = json.loads(content)
    parsed = parse_offline_collection(raw)
    built = _build_tables(parsed["tables"], name)
    return [AgentTable.model_validate(t.model_dump(mode="json")) for t in built]


@pytest.fixture(scope="module")
def discourse_tables() -> list[AgentTable]:
    return _sample_tables("discourse")


def test_discourse_carry_over_residuals_drop_to_the_genuinely_unmappable(discourse_tables):
    before = generate_pg_ddl(discourse_tables)  # normalized type only (pre-#274)
    after = generate_pg_ddl(discourse_tables, source_engine="postgresql")

    assert len(before.residuals) > 1500
    # Only the two PostgreSQL enum types remain: their CREATE TYPE is not collected.
    assert sorted(r["source_type"] for r in after.residuals) == [
        "ai_moderation_setting_type",
        "hotlinked_media_status",
    ]
    ids = {(t.table_name, c.name): c.aurora_type for t in after.tables for c in t.columns}
    assert ids[("admin_notices", "id")] == "BIGINT"


def test_wordpress_carry_over_has_no_residuals():
    tables = _sample_tables("wordpress")
    result = generate_mysql_ddl(tables, source_engine="mysql")
    assert result.residuals == []
    assert "`ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL" in result.full_ddl
    assert "`post_content` LONGTEXT NOT NULL" in result.full_ddl
