from src.contracts.schema_design_input import (
    AgentColumn,
    AgentForeignKey,
    AgentIndex,
    AgentTable,
    ForeignKeyAction,
)
from src.contracts.schema_design_input import NormalizedDataType as N
from src.tools.schema.aurora_common.ddl_generator import generate_pg_ddl


def _users_table():
    return AgentTable(
        table_id="t1",
        table_name="users",
        row_count=1000,
        primary_key=["id"],
        columns=[
            AgentColumn(
                column_name="id",
                normalized_data_type=N.integer,
                nullable=False,
                is_auto_increment=True,
            ),
            AgentColumn(
                column_name="email", normalized_data_type=N.string, max_length=255, nullable=False
            ),
            AgentColumn(
                column_name="status",
                normalized_data_type=N.string,
                max_length=20,
                nullable=False,
                default_value="active",
            ),
        ],
        indexes=[AgentIndex(index_name="ix_users_email", columns=["email"], is_unique=True)],
    )


def test_create_table_columns_and_pk():
    result = generate_pg_ddl([_users_table()])
    ddl = result.full_ddl
    assert 'CREATE TABLE "users"' in ddl
    assert '"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL' in ddl
    assert '"email" VARCHAR(255) NOT NULL' in ddl
    assert "\"status\" VARCHAR(20) NOT NULL DEFAULT 'active'" in ddl
    assert 'PRIMARY KEY ("id")' in ddl


def test_unique_index_emitted():
    result = generate_pg_ddl([_users_table()])
    assert 'CREATE UNIQUE INDEX "ix_users_email" ON "users" ("email")' in result.full_ddl


def test_foreign_key_emitted_after_tables():
    orders = AgentTable(
        table_id="t2",
        table_name="orders",
        row_count=10,
        primary_key=["id"],
        columns=[
            AgentColumn(
                column_name="id",
                normalized_data_type=N.integer,
                nullable=False,
                is_auto_increment=True,
            ),
            AgentColumn(column_name="user_id", normalized_data_type=N.integer, nullable=False),
        ],
        foreign_keys=[
            AgentForeignKey(
                constraint_name="fk_orders_user",
                columns=["user_id"],
                referenced_table="users",
                referenced_columns=["id"],
                on_delete=ForeignKeyAction.CASCADE,
            )
        ],
    )
    result = generate_pg_ddl([_users_table(), orders])
    ddl = result.full_ddl
    assert 'ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_user"' in ddl
    assert 'FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE' in ddl
    # FK must come after both CREATE TABLEs.
    assert ddl.index("ALTER TABLE") > ddl.index('CREATE TABLE "orders"')


def test_residual_marker_for_lengthless_string():
    tbl = AgentTable(
        table_id="t3",
        table_name="notes",
        row_count=1,
        primary_key=["id"],
        columns=[
            AgentColumn(column_name="id", normalized_data_type=N.integer, nullable=False),
            AgentColumn(
                column_name="body", normalized_data_type=N.string, max_length=None, nullable=True
            ),
        ],
    )
    result = generate_pg_ddl([tbl])
    residuals = [r for r in result.residuals if r["column"] == "body"]
    assert len(residuals) == 1
    assert residuals[0]["table"] == "notes"
    assert "length" in residuals[0]["reason"].lower()


def test_structured_tables_carry_provenance():
    result = generate_pg_ddl([_users_table()])
    table = result.tables[0]
    id_col = next(c for c in table.columns if c.name == "id")
    assert id_col.aurora_type == "BIGINT"
    assert id_col.source_type == "integer"
    assert id_col.script_derived is True
    assert id_col.needs_judgment is False
