from src.contracts.schema_design_input import ForeignKeyAction
from src.tools.schema.aurora_common.constraint_translator import (
    default_clause,
    fk_on_delete_clause,
    identity_clause,
    not_null_clause,
)


def test_identity_clause():
    assert identity_clause(True) == " GENERATED BY DEFAULT AS IDENTITY"
    assert identity_clause(False) == ""


def test_not_null_clause():
    assert not_null_clause(False) == " NOT NULL"
    assert not_null_clause(True) == ""


def test_default_clause_types():
    assert default_clause(None) == ""
    assert default_clause(42) == " DEFAULT 42"
    assert default_clause(3.5) == " DEFAULT 3.5"
    assert default_clause(True) == " DEFAULT TRUE"
    assert default_clause(False) == " DEFAULT FALSE"
    assert default_clause("active") == " DEFAULT 'active'"
    assert default_clause("O'Brien") == " DEFAULT 'O''Brien'"


def test_default_clause_passes_through_sql_keywords():
    assert default_clause("CURRENT_TIMESTAMP") == " DEFAULT CURRENT_TIMESTAMP"
    assert default_clause("NULL") == " DEFAULT NULL"


def test_fk_on_delete_clause():
    assert fk_on_delete_clause(ForeignKeyAction.CASCADE) == " ON DELETE CASCADE"
    assert fk_on_delete_clause(ForeignKeyAction.SET_NULL) == " ON DELETE SET NULL"
    assert fk_on_delete_clause(None) == ""
