/**
 * #405: the standalone HTML export's "Access Patterns" stat, Access Pattern
 * Explorer pie/filters/rows and its "Total Patterns"/"Patterns" sub-counts all
 * summed every engine's schema-design access_patterns, including ElastiCache's
 * own cache-pattern design -- the same gap the Results page had before #361
 * (fixed there via utils/cacheLayer.js's ownerSchemaDesigns/
 * cacheAccessPatternCount). The embedded client script has no bundler at
 * runtime, so it can't import those helpers -- extractPatterns() (generated by
 * generateReportScript) needs its own literal mirror.
 *
 * Separate file from ExportReport.cacheLayer.test.js and exportEscaping.test.js
 * on purpose: the embedded script declares top-level `const`s in the jsdom
 * global scope when evaluated, so it can only be loaded once per test file.
 */
import { generateHTMLReport, CACHE_ENGINE_SKIP_EXPR } from '../ExportReport';
import { isCacheEngine, ownerSchemaDesigns, cacheAccessPatternCount } from '../cacheLayer';

const schemaDesigns = (cacheCount) => [
  { target_type: 'dynamodb', content: { access_patterns: [{ pattern_id: 'ddb-1' }, { pattern_id: 'ddb-2' }] } },
  { target_type: 'opensearch', content: { access_patterns: [{ pattern_id: 'os-1' }] } },
  { target_type: 'aurora_mysql', content: { access_patterns: [] } },
  {
    target_type: 'elasticache',
    content: { access_patterns: Array.from({ length: cacheCount }, (_, i) => ({ pattern_id: `ec-${i}` })) },
  },
];

const cacheReportData = (cacheCount = 3) => ({
  jobId: 'job-1',
  exportDate: '2026-10-03T12:00:00Z',
  collector: {},
  schemaDesigns: schemaDesigns(cacheCount),
  queryJourneys: { items: [] },
  results: {
    synthesis: {
      database_name: 'wordpress',
      summary: 'summary',
      reality_check: { after_distribution: { dynamodb: 68, opensearch: 3 } },
      cache_overlay: { engine: 'elasticache', query_count: cacheCount, calls_per_second: 158.85, call_share_percent: 71.5 },
      tco_analysis: { projected_monthly_cost: 823.72, cost_breakdown: [] },
    },
  },
});

// #405: a legacy report has no cache_overlay at all -- ElastiCache is still a
// real owner there (src/report/analysis_report.py only strips a design when
// cache_overlay.engine names it), so its schema design's access patterns must
// stay in the owner total, with no separate "+N cache-layer patterns" note.
const legacyReportData = (cacheCount = 3) => {
  const data = cacheReportData(cacheCount);
  delete data.results.synthesis.cache_overlay;
  data.results.synthesis.reality_check.after_distribution.elasticache = cacheCount;
  return data;
};

const statValue = (doc, label) => [...doc.querySelectorAll('.stat-card')]
  .find((c) => c.querySelector('.stat-label')?.textContent === label)
  ?.querySelector('.stat-value')?.textContent;

const statNote = (doc, label) => [...doc.querySelectorAll('.stat-card')]
  .find((c) => c.querySelector('.stat-label')?.textContent === label)
  ?.querySelector('.stat-note')?.textContent;

describe('generateHTMLReport shell (#405, no script execution)', () => {
  it('counts only owner-engine access patterns in the Access Patterns stat, matching ownerSchemaDesigns', () => {
    const data = cacheReportData(3);
    const expectedOwnerTotal = ownerSchemaDesigns(data.schemaDesigns, true)
      .reduce((sum, d) => sum + d.content.access_patterns.length, 0);
    expect(expectedOwnerTotal).toBe(3); // 2 dynamodb + 1 opensearch + 0 aurora_mysql
    const doc = new DOMParser().parseFromString(generateHTMLReport(data), 'text/html');
    expect(statValue(doc, 'Access Patterns')).toBe('3');
  });

  it('shows the cache-layer pattern count separately, worded like the Results page, plural for N > 1', () => {
    const data = cacheReportData(3);
    expect(cacheAccessPatternCount(data.schemaDesigns, true)).toBe(3);
    const doc = new DOMParser().parseFromString(generateHTMLReport(data), 'text/html');
    expect(statNote(doc, 'Access Patterns')).toBe('+3 cache-layer patterns (not counted above)');
  });

  it('uses the singular form for exactly one cache-layer pattern', () => {
    const doc = new DOMParser().parseFromString(generateHTMLReport(cacheReportData(1)), 'text/html');
    expect(statNote(doc, 'Access Patterns')).toBe('+1 cache-layer pattern (not counted above)');
  });

  it('omits the cache-layer note entirely when there are no cache-layer patterns', () => {
    const doc = new DOMParser().parseFromString(generateHTMLReport(cacheReportData(0)), 'text/html');
    expect(statNote(doc, 'Access Patterns')).toBeUndefined();
  });

  it('the Access Pattern Explorer header count is also owner-only', () => {
    const doc = new DOMParser().parseFromString(generateHTMLReport(cacheReportData(3)), 'text/html');
    expect(doc.getElementById('pattern-count')?.textContent).toBe('3');
  });
});

describe('generateHTMLReport shell: legacy report, no cache_overlay (#405, no script execution)', () => {
  it('counts the elasticache design\'s patterns as owned workload, matching ownerSchemaDesigns(..., false)', () => {
    const data = legacyReportData(3);
    const expectedTotal = ownerSchemaDesigns(data.schemaDesigns, false)
      .reduce((sum, d) => sum + d.content.access_patterns.length, 0);
    expect(expectedTotal).toBe(6); // 2 dynamodb + 1 opensearch + 0 aurora_mysql + 3 elasticache
    const doc = new DOMParser().parseFromString(generateHTMLReport(data), 'text/html');
    expect(statValue(doc, 'Access Patterns')).toBe('6');
    expect(doc.getElementById('pattern-count')?.textContent).toBe('6');
  });

  it('shows no cache-layer note: there is no overlay to call out separately', () => {
    expect(cacheAccessPatternCount(legacyReportData(3).schemaDesigns, false)).toBe(0);
    const doc = new DOMParser().parseFromString(generateHTMLReport(legacyReportData(3)), 'text/html');
    expect(statNote(doc, 'Access Patterns')).toBeUndefined();
  });
});

/**
 * Run the exported report's own embedded <script> in this test's jsdom window,
 * the way a browser does when the file is opened. Mirrors
 * ExportReport.cacheLayer.test.js's loadInteractiveReport; kept local and used
 * exactly once (the script declares top-level consts).
 */
const loadInteractiveReport = (markup) => {
  const parsed = new DOMParser().parseFromString(markup, 'text/html');
  const inline = [...parsed.querySelectorAll('script')].filter((el) => !el.src);
  expect(inline).toHaveLength(1);
  const code = inline[0].textContent;
  parsed.querySelectorAll('script').forEach((el) => el.remove());

  window.Chart = class { destroy() {} };
  jest.spyOn(console, 'log').mockImplementation(() => {});
  document.head.innerHTML = parsed.head.innerHTML;
  document.body.innerHTML = parsed.body.innerHTML;
  const script = document.createElement('script');
  script.textContent = code;
  document.body.appendChild(script);
  document.dispatchEvent(new Event('DOMContentLoaded'));
  return window;
};

describe('embedded extractPatterns script (#405)', () => {
  let doc;

  beforeAll(() => {
    doc = loadInteractiveReport(generateHTMLReport(cacheReportData(3))).document;
  });

  it('drops the cache engine from the pattern count driving the pie/filters/rows', () => {
    // Default browseMode is "pattern"; buildPatternTable() sets pattern-count to
    // filterPatterns().length, which is allPatterns.length with no active filters.
    expect(doc.getElementById('pattern-count').textContent).toBe('3');
  });

  it('never renders an ElastiCache row in the Access Pattern Explorer table', () => {
    const container = doc.getElementById('access-patterns-container');
    expect(container.querySelectorAll('[data-engine="elasticache"]')).toHaveLength(0);
  });

  it('renders every owner-engine row', () => {
    const container = doc.getElementById('access-patterns-container');
    expect(container.querySelectorAll('tbody tr')).toHaveLength(3);
  });
});

describe('CACHE_ENGINE_SKIP_EXPR (#405, the embedded script\'s mirror of isCacheEngine + the hasOverlay guard)', () => {
  it('agrees with cacheLayer.js\'s isCacheEngine, gated on hasCacheOverlay, for the same inputs', () => {
    // eslint-disable-next-line no-new-func -- evaluating the exact expression the
    // generated script embeds, to assert the two copies haven't drifted apart.
    const predicate = new Function(
      'design', 'hasCacheOverlay', 'return (' + CACHE_ENGINE_SKIP_EXPR + ');'
    );
    [true, false].forEach((hasCacheOverlay) => {
      ['elasticache', 'dynamodb', 'opensearch', 'aurora_mysql'].forEach((engine) => {
        expect(predicate({ target_type: engine }, hasCacheOverlay))
          .toBe(hasCacheOverlay && isCacheEngine(engine));
      });
    });
  });

  // sync_report_template.py requires every `script += '...';` line in
  // generateReportScript to be its own single-quoted literal, so extractPatterns
  // can't splice CACHE_ENGINE_SKIP_EXPR in at build time -- it hardcodes the same
  // text instead. This asserts the hardcoded copy embedded in the actual
  // generated output still matches the constant above, so an edit to one
  // without the other fails here.
  it('the generated script\'s hardcoded filter still matches the constant', () => {
    const markup = generateHTMLReport(cacheReportData(3));
    const scriptText = [...new DOMParser().parseFromString(markup, 'text/html').querySelectorAll('script')]
      .map((el) => el.textContent).join('\n');
    expect(scriptText).toContain('if (' + CACHE_ENGINE_SKIP_EXPR + ') return;');
  });
});
