/**
 * #405/#429 part 2: the standalone HTML export's "Access Patterns" stat and
 * the explorer's "Total Patterns"/"Patterns" sub-counts stay owner-only (the
 * same gap the Results page had before #361, fixed there via
 * utils/cacheLayer.js's ownerSchemaDesigns/cacheAccessPatternCount) -- but the
 * Access Pattern Explorer itself must still be able to browse the cache
 * layer's own key designs (#429 part 2), as a distinct, tagged group after the
 * owner rows, instead of #405 dropping them from the explorer entirely. The
 * embedded client script has no bundler at runtime, so it can't import
 * cacheLayer.js's helpers -- extractPatterns()/buildPatternTable()/
 * buildSourceTableTable() (generated by generateReportScript) need their own
 * literal mirror.
 *
 * Separate file from ExportReport.cacheLayer.test.js and exportEscaping.test.js
 * on purpose: the embedded script declares top-level `const`s in the jsdom
 * global scope when evaluated, so it can only be loaded once per test file.
 */
import { generateHTMLReport, CACHE_ROW_TAG_EXPR, CACHE_LAYER_SUFFIX } from '../ExportReport';
import { isCacheEngine, ownerSchemaDesigns, cacheAccessPatternCount } from '../cacheLayer';

const schemaDesigns = (cacheCount) => [
  { target_type: 'dynamodb', content: { access_patterns: [{ pattern_id: 'ddb-1' }, { pattern_id: 'ddb-2' }] } },
  { target_type: 'opensearch', content: { access_patterns: [{ pattern_id: 'os-1' }] } },
  { target_type: 'aurora_mysql', content: { access_patterns: [] } },
  {
    target_type: 'elasticache',
    content: {
      key_designs: [
        { key_pattern: 'ec-key-0', data_type: 'hash', ttl_seconds: 900 },
      ],
      access_patterns: Array.from({ length: cacheCount }, (_, i) => ({
        pattern_id: `ec-${i}`,
        operation: 'HGET',
        key_pattern: `ec-key-${i}`,
      })),
    },
  },
];

const cacheReportData = (cacheCount = 3) => ({
  jobId: 'job-1',
  exportDate: '2026-10-03T12:00:00Z',
  collector: {},
  schemaDesigns: schemaDesigns(cacheCount),
  queryJourneys: { items: [] },
  results: {
    synthesis: {
      database_name: 'wordpress',
      summary: 'summary',
      reality_check: { after_distribution: { dynamodb: 68, opensearch: 3 } },
      cache_overlay: { engine: 'elasticache', query_count: cacheCount, calls_per_second: 158.85, call_share_percent: 71.5 },
      tco_analysis: { projected_monthly_cost: 823.72, cost_breakdown: [] },
    },
  },
});

// #405: a legacy report has no cache_overlay at all -- ElastiCache is still a
// real owner there (src/report/analysis_report.py only strips a design when
// cache_overlay.engine names it), so its schema design's access patterns must
// stay in the owner total, with no separate "+N cache-layer patterns" note.
const legacyReportData = (cacheCount = 3) => {
  const data = cacheReportData(cacheCount);
  delete data.results.synthesis.cache_overlay;
  data.results.synthesis.reality_check.after_distribution.elasticache = cacheCount;
  return data;
};

const statValue = (doc, label) => [...doc.querySelectorAll('.stat-card')]
  .find((c) => c.querySelector('.stat-label')?.textContent === label)
  ?.querySelector('.stat-value')?.textContent;

const statNote = (doc, label) => [...doc.querySelectorAll('.stat-card')]
  .find((c) => c.querySelector('.stat-label')?.textContent === label)
  ?.querySelector('.stat-note')?.textContent;

describe('generateHTMLReport shell (#405, no script execution)', () => {
  it('counts only owner-engine access patterns in the Access Patterns stat, matching ownerSchemaDesigns', () => {
    const data = cacheReportData(3);
    const expectedOwnerTotal = ownerSchemaDesigns(data.schemaDesigns, true)
      .reduce((sum, d) => sum + d.content.access_patterns.length, 0);
    expect(expectedOwnerTotal).toBe(3); // 2 dynamodb + 1 opensearch + 0 aurora_mysql
    const doc = new DOMParser().parseFromString(generateHTMLReport(data), 'text/html');
    expect(statValue(doc, 'Access Patterns')).toBe('3');
  });

  it('shows the cache-layer pattern count separately, worded like the Results page, plural for N > 1', () => {
    const data = cacheReportData(3);
    expect(cacheAccessPatternCount(data.schemaDesigns, true)).toBe(3);
    const doc = new DOMParser().parseFromString(generateHTMLReport(data), 'text/html');
    expect(statNote(doc, 'Access Patterns')).toBe('+3 cache-layer patterns (not counted above)');
  });

  it('uses the singular form for exactly one cache-layer pattern', () => {
    const doc = new DOMParser().parseFromString(generateHTMLReport(cacheReportData(1)), 'text/html');
    expect(statNote(doc, 'Access Patterns')).toBe('+1 cache-layer pattern (not counted above)');
  });

  it('omits the cache-layer note entirely when there are no cache-layer patterns', () => {
    const doc = new DOMParser().parseFromString(generateHTMLReport(cacheReportData(0)), 'text/html');
    expect(statNote(doc, 'Access Patterns')).toBeUndefined();
  });

  // #429 part 2: the explorer's own header count is no longer owner-only --
  // it now breaks the combined total down into owned vs. cache layer, so the
  // cache layer's rows (browsable below) are accounted for in the header that
  // introduces them. The "Access Patterns" stat above stays owner-only.
  it('the Access Pattern Explorer header count breaks owned vs. cache layer out', () => {
    const doc = new DOMParser().parseFromString(generateHTMLReport(cacheReportData(3)), 'text/html');
    expect(doc.getElementById('pattern-count')?.textContent).toBe('6 (3 owned + 3 cache layer)');
  });

  it('the explorer header count is a bare number when there is no cache layer at all', () => {
    const doc = new DOMParser().parseFromString(generateHTMLReport(cacheReportData(0)), 'text/html');
    expect(doc.getElementById('pattern-count')?.textContent).toBe('3');
  });
});

describe('generateHTMLReport shell: legacy report, no cache_overlay (#405, no script execution)', () => {
  it('counts the elasticache design\'s patterns as owned workload, matching ownerSchemaDesigns(..., false)', () => {
    const data = legacyReportData(3);
    const expectedTotal = ownerSchemaDesigns(data.schemaDesigns, false)
      .reduce((sum, d) => sum + d.content.access_patterns.length, 0);
    expect(expectedTotal).toBe(6); // 2 dynamodb + 1 opensearch + 0 aurora_mysql + 3 elasticache
    const doc = new DOMParser().parseFromString(generateHTMLReport(data), 'text/html');
    expect(statValue(doc, 'Access Patterns')).toBe('6');
    expect(doc.getElementById('pattern-count')?.textContent).toBe('6');
  });

  it('shows no cache-layer note: there is no overlay to call out separately', () => {
    expect(cacheAccessPatternCount(legacyReportData(3).schemaDesigns, false)).toBe(0);
    const doc = new DOMParser().parseFromString(generateHTMLReport(legacyReportData(3)), 'text/html');
    expect(statNote(doc, 'Access Patterns')).toBeUndefined();
  });
});

/**
 * Run the exported report's own embedded <script> in this test's jsdom window,
 * the way a browser does when the file is opened. Mirrors
 * ExportReport.cacheLayer.test.js's loadInteractiveReport; kept local and used
 * exactly once (the script declares top-level consts).
 */
const loadInteractiveReport = (markup) => {
  const parsed = new DOMParser().parseFromString(markup, 'text/html');
  const inline = [...parsed.querySelectorAll('script')].filter((el) => !el.src);
  expect(inline).toHaveLength(1);
  const code = inline[0].textContent;
  parsed.querySelectorAll('script').forEach((el) => el.remove());

  window.Chart = class { destroy() {} };
  jest.spyOn(console, 'log').mockImplementation(() => {});
  document.head.innerHTML = parsed.head.innerHTML;
  document.body.innerHTML = parsed.body.innerHTML;
  const script = document.createElement('script');
  script.textContent = code;
  document.body.appendChild(script);
  document.dispatchEvent(new Event('DOMContentLoaded'));
  return window;
};

// One shared load for every "embedded script" assertion below -- the script
// declares top-level `const`s in the jsdom global scope when evaluated, so it
// can only be loaded once per test file.
let doc;

beforeAll(() => {
  doc = loadInteractiveReport(generateHTMLReport(cacheReportData(3))).document;
});

describe('embedded extractPatterns/buildPatternTable script (#429 part 2)', () => {
  it('the explorer header count breaks owned vs. cache layer out, driven by the rendered rows', () => {
    expect(doc.getElementById('pattern-count').textContent).toBe('6 (3 owned + 3 cache layer)');
  });

  it('renders every owner-engine row in the first (owner) table', () => {
    const container = doc.getElementById('access-patterns-container');
    const tables = container.querySelectorAll('table');
    expect(tables).toHaveLength(2); // owner table + cache-layer table
    expect(tables[0].querySelectorAll('tbody tr')).toHaveLength(3);
  });

  it('renders the cache layer\'s own rows in a second, separately labelled table after the owner rows', () => {
    const container = doc.getElementById('access-patterns-container');
    const heading = container.querySelector('div.cache-layer-section-title');
    expect(heading.textContent).toBe('ElastiCache (cache layer) (3)');
    const tables = container.querySelectorAll('table');
    expect(tables[1].querySelectorAll('tbody tr')).toHaveLength(3);
    expect(tables[1].querySelectorAll('[data-engine="elasticache"]')).toHaveLength(3);
  });

  it('tags every cache-layer row\'s engine badge with the same "(cache layer)" suffix as elsewhere in the report', () => {
    const container = doc.getElementById('access-patterns-container');
    const cacheRow = container.querySelectorAll('table')[1].querySelector('tbody tr');
    expect(cacheRow.querySelector('[data-engine="elasticache"]').textContent).toBe('ElastiCache' + CACHE_LAYER_SUFFIX);
  });

  it('joins the cache design\'s key_designs TTL into the Destination column by key_pattern', () => {
    const container = doc.getElementById('access-patterns-container');
    const firstCacheRow = container.querySelectorAll('table')[1].querySelector('tbody tr');
    // ec-key-0 has a matching key design (ttl_seconds: 900); the fixture's other
    // cache rows (ec-key-1, ec-key-2) have no matching key_designs entry.
    expect(firstCacheRow.textContent).toContain('ec-key-0 · TTL 900s');
  });

  it('the pattern-detail modal shows a cache row\'s TTL and key data type, like the Results page modal', () => {
    window.showPatternDetails('ec-0');
    const body = doc.getElementById('pattern-modal-body').textContent;
    expect(body).toContain('TTL900s');
    expect(body).toContain('Key data typehash');
    window.closePatternModal();
  });

  it('the pattern-detail modal of an owner row has no cache metrics', () => {
    window.showPatternDetails('ddb-1');
    const body = doc.getElementById('pattern-modal-body').textContent;
    expect(body).not.toContain('Key data type');
    window.closePatternModal();
  });

  it('the cache-layer section title is not a heading element (the export has no h2 level, see axe heading-order)', () => {
    const container = doc.getElementById('access-patterns-container');
    expect(container.querySelector('h3, h4')).toBeNull();
  });
});

describe('embedded createCharts script: the engine pie stays owner-only (#429 part 2)', () => {
  it('never counts the cache layer in the engine pie\'s own data (owner-only, like the "Access Patterns" stat) -- its own legend line carries the count instead', () => {
    const legend = doc.getElementById('engine-cache-legend');
    expect(legend.textContent).toBe('ElastiCache (cache layer): 3');
  });
});

describe('CACHE_ROW_TAG_EXPR (#429 part 2, the embedded script\'s mirror of isCacheEngine)', () => {
  it('agrees with cacheLayer.js\'s isCacheEngine for the same inputs', () => {
    // eslint-disable-next-line no-new-func -- evaluating the exact expression the
    // generated script embeds, to assert the two copies haven't drifted apart.
    const predicate = new Function(
      'cacheEngine', 'engine', 'return (' + CACHE_ROW_TAG_EXPR + ');'
    );
    ['elasticache', 'dynamodb', 'opensearch', 'aurora_mysql'].forEach((engine) => {
      expect(predicate('elasticache', engine)).toBe(isCacheEngine(engine));
      expect(predicate(null, engine)).toBe(false);
    });
  });

  // sync_report_template.py requires every `script += '...';` line in
  // generateReportScript to be its own single-quoted literal, so
  // extractPatterns can't splice CACHE_ROW_TAG_EXPR in at build time -- it
  // hardcodes the same text instead. This asserts the hardcoded copy embedded
  // in the actual generated output still matches the constant above, so an
  // edit to one without the other fails here.
  it('the generated script\'s hardcoded tag still matches the constant', () => {
    const markup = generateHTMLReport(cacheReportData(3));
    const scriptText = [...new DOMParser().parseFromString(markup, 'text/html').querySelectorAll('script')]
      .map((el) => el.textContent).join('\n');
    expect(scriptText).toContain('const isCacheLayer = ' + CACHE_ROW_TAG_EXPR + ';');
  });
});
