"""SQL-fragment helpers for Aurora PostgreSQL column/constraint generation.

Each helper returns a leading-space-prefixed fragment (or empty string) so the
DDL generator can concatenate them without worrying about spacing.
"""

from __future__ import annotations

from src.contracts.schema_design_input import ForeignKeyAction

# Default values that are SQL expressions/keywords, not literals — passed through
# verbatim rather than quoted.
_SQL_KEYWORD_DEFAULTS = {
    "CURRENT_TIMESTAMP",
    "CURRENT_DATE",
    "CURRENT_TIME",
    "NOW()",
    "NULL",
    "TRUE",
    "FALSE",
}


def identity_clause(is_auto_increment: bool | None) -> str:
    """PostgreSQL IDENTITY replaces MySQL AUTO_INCREMENT / Oracle sequences."""
    return " GENERATED BY DEFAULT AS IDENTITY" if is_auto_increment else ""


def not_null_clause(nullable: bool) -> str:
    return "" if nullable else " NOT NULL"


def is_expression_default(default_value: object) -> bool:
    """A string default that is SQL (a cast or a call), not a literal value.

    It is still rendered as a quoted literal (parsing ``'lit'::type`` is #156),
    so the draft flags it for review.
    """
    if not isinstance(default_value, str):
        return False
    text = default_value.strip()
    return text.upper() not in _SQL_KEYWORD_DEFAULTS and ("::" in text or "(" in text)


def default_clause(
    default_value: str | int | float | bool | None, *, backslash_escapes: bool = False
) -> str:
    """Render a column DEFAULT clause, quoting string literals safely.

    ``backslash_escapes`` is for MySQL, where a backslash escapes the next
    character inside a string literal (unless NO_BACKSLASH_ESCAPES is set):
    without doubling it, ``x\\'`` would end the literal and let the rest of
    the default inject DDL. Doubled, the value is kept under the default
    sql_mode and the literal still cannot be closed early under
    NO_BACKSLASH_ESCAPES.
    """
    if default_value is None:
        return ""
    if isinstance(default_value, bool):
        return f" DEFAULT {'TRUE' if default_value else 'FALSE'}"
    if isinstance(default_value, (int, float)):
        return f" DEFAULT {default_value}"
    # string
    if default_value.strip().upper() in _SQL_KEYWORD_DEFAULTS:
        return f" DEFAULT {default_value.strip()}"
    escaped = default_value.replace("\\", "\\\\") if backslash_escapes else default_value
    escaped = escaped.replace("'", "''")
    return f" DEFAULT '{escaped}'"


def fk_on_delete_clause(action: ForeignKeyAction | None) -> str:
    return f" ON DELETE {action.value}" if action is not None else ""


def mysql_auto_increment_clause(is_auto_increment: bool | None) -> str:
    """MySQL AUTO_INCREMENT replaces PostgreSQL IDENTITY."""
    return " AUTO_INCREMENT" if is_auto_increment else ""
