"""SQL-fragment helpers for Aurora PostgreSQL column/constraint generation.

Each helper returns a leading-space-prefixed fragment (or empty string) so the
DDL generator can concatenate them without worrying about spacing.
"""

from __future__ import annotations

from src.contracts.schema_design_input import ForeignKeyAction

# Default values that are SQL expressions/keywords, not literals — passed through
# verbatim rather than quoted.
_SQL_KEYWORD_DEFAULTS = {
    "CURRENT_TIMESTAMP",
    "CURRENT_DATE",
    "CURRENT_TIME",
    "NOW()",
    "NULL",
    "TRUE",
    "FALSE",
}


def identity_clause(is_auto_increment: bool | None) -> str:
    """PostgreSQL IDENTITY replaces MySQL AUTO_INCREMENT / Oracle sequences."""
    return " GENERATED BY DEFAULT AS IDENTITY" if is_auto_increment else ""


def not_null_clause(nullable: bool) -> str:
    return "" if nullable else " NOT NULL"


def default_clause(default_value: str | int | float | bool | None) -> str:
    """Render a column DEFAULT clause, quoting string literals safely."""
    if default_value is None:
        return ""
    if isinstance(default_value, bool):
        return f" DEFAULT {'TRUE' if default_value else 'FALSE'}"
    if isinstance(default_value, (int, float)):
        return f" DEFAULT {default_value}"
    # string
    if default_value.strip().upper() in _SQL_KEYWORD_DEFAULTS:
        return f" DEFAULT {default_value.strip()}"
    escaped = default_value.replace("'", "''")
    return f" DEFAULT '{escaped}'"


def fk_on_delete_clause(action: ForeignKeyAction | None) -> str:
    return f" ON DELETE {action.value}" if action is not None else ""


def mysql_auto_increment_clause(is_auto_increment: bool | None) -> str:
    """MySQL AUTO_INCREMENT replaces PostgreSQL IDENTITY."""
    return " AUTO_INCREMENT" if is_auto_increment else ""
