#!/usr/bin/env python3
"""Extract the interactive-report template out of the React exporter.

``src/ui/src/utils/ExportReport.js`` is the single source of truth for what the
interactive analysis report *looks like*. Its ``generateHTMLReport`` is a pure
function of one JSON object: the CSS is a static string constant, the ~13
client-side functions are static text, and the only data-dependent output is
``const DATA = {...}``.

This script mechanically lifts those static parts into three files that the ATX
synthesis renderer substitutes into:

    src/atx_orchestrator/runtime/templates/analysis_report.css       <- REPORT_CSS
    src/atx_orchestrator/runtime/templates/analysis_report.js        <- generateReportScript body
    src/atx_orchestrator/runtime/templates/analysis_report.html.tpl  <- generateHTMLReport shell

Because the extraction is mechanical, ``tests/unit/atx_orchestrator/test_report_template_sync.py``
can re-run it and assert the committed files still match. A UI change that is not
propagated therefore fails CI instead of silently producing a stale ATX report.

Usage:
    uv run python scripts/sync_report_template.py            # write the files
    uv run python scripts/sync_report_template.py --check     # exit 1 if out of date
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "src" / "ui" / "src" / "utils" / "ExportReport.js"
TEMPLATE_DIR = REPO_ROOT / "src" / "atx_orchestrator" / "runtime" / "templates"

CSS_OUT = TEMPLATE_DIR / "analysis_report.css"
JS_OUT = TEMPLATE_DIR / "analysis_report.js"
HTML_OUT = TEMPLATE_DIR / "analysis_report.html.tpl"

GENERATED_BANNER = (
    "GENERATED by scripts/sync_report_template.py from "
    "src/ui/src/utils/ExportReport.js -- do not edit by hand."
)

# The ``${...}`` expressions in generateHTMLReport's returned template literal,
# mapped to the placeholder the Python renderer fills. Order matters: the two
# database_name entries differ only in their fallback, so the more specific one
# must be replaced first.
#
# Kept as an explicit table rather than a generic ``${...}`` regex on purpose --
# a new interpolation in the React shell should fail loudly here (see
# _assert_no_unmapped_interpolations) rather than silently become a literal
# "${...}" in the customer's report.
SHELL_SUBSTITUTIONS: list[tuple[str, str]] = [
    ("${escapeHtml(jobId)}", "__TITLE__"),
    ("${new Date(exportDate).toLocaleString()}", "__EXPORT_DATE__"),
    ("${results?.synthesis?.database_name || 'N/A'}", "__DATABASE_NAME__"),
    ("${results?.synthesis?.database_name || '—'}", "__DATABASE_NAME__"),
    ("${results?.synthesis?.summary || 'No summary available.'}", "__SUMMARY__"),
    ("${engineBadges}", "__ENGINE_BADGES__"),
    ("${projectedCost}", "__PROJECTED_COST__"),
    ("${totalPatterns}", "__TOTAL_PATTERNS__"),
    ("${jobId}", "__JOB_ID__"),
]

# Injection points the ATX renderer adds on top of the React shell. Each is a
# placeholder the renderer fills with content the browser export has no need for:
# self-identifying metadata (naming convention), an offline Chart.js bundle, and
# an honest banner when the query-journey set was sampled rather than complete.
CHART_CDN_TAG = (
    '<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>'
)


def _unescape_js_single_quoted(literal: str) -> str:
    """Decode the body of a JavaScript single-quoted string literal."""
    out: list[str] = []
    i = 0
    simple = {
        "n": "\n",
        "t": "\t",
        "r": "\r",
        "b": "\b",
        "f": "\f",
        "v": "\v",
        "0": "\0",
        "'": "'",
        '"': '"',
        "\\": "\\",
        "/": "/",
        "`": "`",
        "$": "$",
    }
    while i < len(literal):
        ch = literal[i]
        if ch != "\\":
            out.append(ch)
            i += 1
            continue
        i += 1
        if i >= len(literal):
            raise ValueError("string literal ends in a trailing backslash")
        esc = literal[i]
        if esc in simple:
            out.append(simple[esc])
            i += 1
        elif esc == "u":
            if literal[i + 1] == "{":
                close = literal.index("}", i)
                out.append(chr(int(literal[i + 2 : close], 16)))
                i = close + 1
            else:
                out.append(chr(int(literal[i + 1 : i + 5], 16)))
                i += 5
        elif esc == "x":
            out.append(chr(int(literal[i + 1 : i + 3], 16)))
            i += 3
        else:
            # Unrecognised escape: JS drops the backslash.
            out.append(esc)
            i += 1
    return "".join(out)


def _read_source() -> list[str]:
    if not SOURCE.exists():
        raise SystemExit(f"source not found: {SOURCE}")
    return SOURCE.read_text(encoding="utf-8").split("\n")


def extract_css(lines: list[str]) -> str:
    """Return REPORT_CSS with its JS concatenation evaluated."""
    start = next(i for i, ln in enumerate(lines) if ln.startswith("const REPORT_CSS ="))
    parts: list[str] = []
    first = lines[start].split("=", 1)[1].strip()
    if first != "'\\n' +":
        raise SystemExit(f"unexpected REPORT_CSS opening at line {start + 1}: {first!r}")
    parts.append("\n")

    i = start + 1
    piece = re.compile(r"^\s*'(.*)'\s*(\+|;)\s*$")
    while i < len(lines):
        m = piece.match(lines[i])
        if not m:
            raise SystemExit(f"unexpected REPORT_CSS line {i + 1}: {lines[i]!r}")
        parts.append(_unescape_js_single_quoted(m.group(1)))
        if m.group(2) == ";":
            break
        i += 1
    else:
        raise SystemExit("REPORT_CSS was never terminated")
    return "".join(parts)


def extract_script_body(lines: list[str]) -> str:
    """Return the static body of generateReportScript.

    Skips the opening ``<script>`` tag and the two ``const`` declarations
    (DATA, ENGINE_LABELS) -- those are the dynamic part and the HTML template
    emits them -- and stops before the closing ``</script>`` tag for the same
    reason. Colours are deliberately absent: they live in the CSS palette and the
    script reads them back with ``paletteColor()``.
    """
    start = next(i for i, ln in enumerate(lines) if ln.startswith("const generateReportScript ="))
    end = next(i for i, ln in enumerate(lines[start:], start) if ln.rstrip() == "  return script;")

    append = re.compile(r"^\s*script \+= '(.*)';\s*$")
    skip_prefixes = (
        "  <script>",
        "    const DATA = ",
        "    const ENGINE_LABELS = ",
    )

    out: list[str] = []
    for raw in lines[start:end]:
        stripped = raw.strip()
        if not stripped or stripped.startswith("//"):
            continue
        m = append.match(raw)
        if not m:
            # Declaration/destructuring lines inside the arrow function body.
            continue
        chunk = _unescape_js_single_quoted(m.group(1))
        if any(chunk.startswith(p) for p in skip_prefixes):
            continue
        if chunk.strip() == "</script>":
            continue
        out.append(chunk)

    body = "".join(out)
    if "function extractPatterns" not in body:
        raise SystemExit("extracted script body is missing extractPatterns -- extraction broke")
    return body


def extract_shell(lines: list[str]) -> str:
    """Return the generateHTMLReport template literal as a placeholder template."""
    start = next(i for i, ln in enumerate(lines) if ln.rstrip() == "  return `<!DOCTYPE html>")
    end = next(i for i, ln in enumerate(lines[start:], start) if ln.rstrip() == "</html>`;")

    shell = "\n".join(lines[start : end + 1])
    shell = shell.replace("  return `", "", 1)
    shell = shell[: shell.rindex("`;")]

    for expr, placeholder in SHELL_SUBSTITUTIONS:
        shell = shell.replace(expr, placeholder)

    # The React exporter calls generateReportScript() inline; we splice in the
    # const block plus the extracted body instead.
    shell = shell.replace(
        "${generateReportScript(data, ENGINE_LABELS)}",
        "__SCRIPT__",
    )
    # CSS and the Chart.js tag become placeholders so the renderer can inline
    # both (offline-safe) instead of depending on a CDN at view time.
    shell = shell.replace("<style>${REPORT_CSS}</style>", "<style>\n__CSS__\n  </style>")
    shell = shell.replace(CHART_CDN_TAG, "__CHART_JS__")

    # ATX-only injection points.
    shell = shell.replace("</head>", "__META__\n</head>", 1)
    shell = shell.replace('<div class="container">', '<div class="container">\n__BANNER__', 1)
    shell = shell.replace("  </div>\n\n__SCRIPT__", "__PROVENANCE__\n  </div>\n\n__SCRIPT__", 1)

    _assert_no_unmapped_interpolations(shell)
    return shell


def _assert_no_unmapped_interpolations(shell: str) -> None:
    leftover = re.findall(r"\$\{[^}]*\}", shell)
    if leftover:
        raise SystemExit(
            "ExportReport.js has interpolations this script does not know how to map: "
            + ", ".join(sorted(set(leftover)))
            + "\nAdd them to SHELL_SUBSTITUTIONS (and fill them in "
            "src/atx_orchestrator/runtime/analysis_report.py)."
        )


def build() -> dict[Path, str]:
    lines = _read_source()
    css = extract_css(lines)
    script = extract_script_body(lines)
    shell = extract_shell(lines)

    for placeholder in ("__CSS__", "__SCRIPT__", "__META__", "__BANNER__", "__PROVENANCE__"):
        if placeholder not in shell:
            raise SystemExit(f"shell template is missing {placeholder}")

    return {
        CSS_OUT: f"/* {GENERATED_BANNER} */\n{css}",
        JS_OUT: f"// {GENERATED_BANNER}\n{script}",
        HTML_OUT: f"<!-- {GENERATED_BANNER} -->\n{shell}",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed templates differ from the extraction",
    )
    args = parser.parse_args()

    generated = build()

    if args.check:
        stale = [p for p, content in generated.items() if _read_or_none(p) != content]
        if stale:
            for p in stale:
                print(f"OUT OF DATE: {p.relative_to(REPO_ROOT)}", file=sys.stderr)
            print(
                "\nExportReport.js changed. Run: uv run python scripts/sync_report_template.py",
                file=sys.stderr,
            )
            return 1
        print("templates are up to date")
        return 0

    TEMPLATE_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in generated.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)} ({len(content):,} bytes)")
    return 0


def _read_or_none(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return None


if __name__ == "__main__":
    raise SystemExit(main())
