// GENERATED by scripts/sync_report_template.py from src/ui/src/utils/ExportReport.js -- do not edit by hand.

    // The palette lives only in the CSS :root block. Charts and SVG need real
    // colour values, so read the custom properties back at runtime -- the
    // computed value of a custom property has its var() references resolved.
    const PALETTE_CACHE = {};
    function paletteColor(name) {
      if (!(name in PALETTE_CACHE)) {
        PALETTE_CACHE[name] = getComputedStyle(document.documentElement).getPropertyValue(name).trim();
      }
      return PALETTE_CACHE[name];
    }
    function engineColor(engine) { return paletteColor('--engine-' + engine) || paletteColor('--engine-fallback'); }
    function opColor(op) { return paletteColor('--op-' + op) || paletteColor('--engine-fallback'); }
    function engineBadge(engine, label) {
      return '<span class="badge" data-engine="' + escapeHtml(engine) + '">' + escapeHtml(label) + '</span>';
    }

    // Helper function to escape HTML to prevent XSS
    function escapeHtml(text) {
      if (text == null) return '';
      const div = document.createElement('div');
      div.textContent = String(text);
      return div.innerHTML;
    }

    // Create query journey lookup by query_id
    const QUERY_JOURNEY_LOOKUP = {};
    if (DATA.queryJourneys) {
      const journeyItems = DATA.queryJourneys.items || [];
      journeyItems.forEach(item => {
        if (item && item.query_id) {
          QUERY_JOURNEY_LOOKUP[item.query_id] = item;
        }
      });
      console.log('Query Journey Lookup created with', Object.keys(QUERY_JOURNEY_LOOKUP).length, 'items');
    }

    let engineChart, operationChart;
    let activeFilters = { engines: [], operations: [], text: '' };
    let allPatterns = [];
    let sourceTableGroups = [];
    let browseMode = 'pattern';
    const PAGE_SIZE = 10;
    let currentPage = 1;

    function extractPatterns() {
      const patterns = [];
      DATA.schemaDesigns.forEach(design => {
        const engine = design.target_type;
        const content = design.content || {};
        (content.access_patterns || []).forEach(ap => {
          const opCategory = getOpCategory(ap.operation || ap.http_method);
          patterns.push({
            id: ap.pattern_id || ap.name || (engine + '-' + patterns.length),
            engine, operation: ap.operation || ap.http_method || '—', opCategory,
            sourceTables: (ap.source_tables || []).map(t => t.split('.').pop()).join(', '),
            sourceTablesArray: (ap.source_tables || []).map(t => t.split('.').pop()),
            destTable: ap.table_name || ap.key_pattern || ap.index_or_stream || ap.index || ap.collection || '—',
            description: ap.description || ap.name || '', gsiName: ap.gsi_name || null
          });
        });
      });
      return patterns;
    }

    function buildSourceTableGroups() {
      const filtered = filterPatterns();
      const groups = {};
      filtered.forEach(ap => {
        ap.sourceTablesArray.forEach(table => {
          if (!groups[table]) {
            groups[table] = { table, engines: new Set(), destTables: new Set(), patterns: [], convergesFrom: new Set() };
          }
          groups[table].engines.add(ap.engine);
          if (ap.destTable !== '—') groups[table].destTables.add(ap.destTable);
          groups[table].patterns.push(ap);
        });
      });
      const destToSources = {};
      filtered.forEach(ap => {
        if (ap.destTable !== '—') {
          if (!destToSources[ap.destTable]) destToSources[ap.destTable] = new Set();
          ap.sourceTablesArray.forEach(t => destToSources[ap.destTable].add(t));
        }
      });
      Object.values(groups).forEach(g => {
        g.destTables.forEach(dt => {
          const sources = destToSources[dt];
          if (sources && sources.size > 1) {
            sources.forEach(s => { if (s !== g.table) g.convergesFrom.add(s); });
          }
        });
      });
      return Object.values(groups).sort((a, b) => b.patterns.length - a.patterns.length);
    }

    function switchBrowseMode(mode) {
      browseMode = mode;
      document.querySelectorAll('.toggle-btn').forEach(btn => btn.classList.remove('active'));
      event.target.classList.add('active');
      currentPage = 1;
      buildTable();
    }

    function getOpCategory(op) {
      if (!op) return 'read';
      if (/get|read|find|scan|query|select/i.test(op)) return 'read';
      if (/put|insert|create|write|set|add/i.test(op)) return 'write';
      if (/search|agg|match/i.test(op)) return 'search';
      if (/update|modify|patch/i.test(op)) return 'update';
      if (/delete|remove/i.test(op)) return 'delete';
      return 'read';
    }

    function filterPatterns() {
      let filtered = [...allPatterns];
      if (activeFilters.engines.length > 0) filtered = filtered.filter(p => activeFilters.engines.includes(p.engine));
      if (activeFilters.operations.length > 0) filtered = filtered.filter(p => activeFilters.operations.includes(p.opCategory));
      if (activeFilters.text) {
        const text = activeFilters.text.toLowerCase();
        filtered = filtered.filter(p => p.id.toLowerCase().includes(text) || p.engine.toLowerCase().includes(text) || p.operation.toLowerCase().includes(text) || p.sourceTables.toLowerCase().includes(text) || p.destTable.toLowerCase().includes(text) || p.description.toLowerCase().includes(text));
      }
      return filtered;
    }

    function updateFilterDisplay() {
      const container = document.getElementById('active-filters');
      const chips = [];
      activeFilters.engines.forEach(e => {
        chips.push('<span class="filter-chip">Engine = ' + e + ' <button onclick="removeFilter(\'engine\', \'' + e + '\')">×</button></span>');
      });
      activeFilters.operations.forEach(o => {
        chips.push('<span class="filter-chip">Operation = ' + o + ' <button onclick="removeFilter(\'operation\', \'' + o + '\')">×</button></span>');
      });
      container.innerHTML = chips.join('');
    }

    function removeFilter(type, value) {
      if (type === 'engine') activeFilters.engines = activeFilters.engines.filter(e => e !== value);
      else if (type === 'operation') activeFilters.operations = activeFilters.operations.filter(o => o !== value);
      updateFilterDisplay();
      buildTable();
      updateCharts();
    }

    function clearAllFilters() {
      activeFilters = { engines: [], operations: [], text: '' };
      document.getElementById('filter-input').value = '';
      updateFilterDisplay();
      buildTable();
      updateCharts();
    }

    function buildTable() {
      if (browseMode === 'pattern') buildPatternTable();
      else buildSourceTableTable();
    }

    function buildPatternTable() {
      const filtered = filterPatterns();
      document.getElementById('pattern-count').textContent = filtered.length;
      const start = (currentPage - 1) * PAGE_SIZE;
      const paginated = filtered.slice(start, start + PAGE_SIZE);
      const totalPages = Math.ceil(filtered.length / PAGE_SIZE);
      let html = '<table><thead><tr><th class="nowrap">Pattern ID</th><th>Operation</th><th>Engine</th><th>Source Tables</th><th>Destination</th><th>Description</th></tr></thead><tbody>';
      paginated.forEach(p => {
        html += '<tr onclick="showPatternDetails(\'' + escapeHtml(p.id) + '\')">';
        html += '<td class="nowrap"><span class="link">' + escapeHtml(p.id.slice(0, 8)) + '</span></td>';
        html += '<td>' + escapeHtml(p.operation) + '</td>';
        html += '<td>' + engineBadge(p.engine, ENGINE_LABELS[p.engine] || p.engine) + '</td>';
        html += '<td>' + escapeHtml(p.sourceTables) + '</td>';
        html += '<td>' + escapeHtml(p.destTable) + (p.gsiName ? ' (GSI: ' + p.gsiName + ')' : '') + '</td>';
        html += '<td>' + escapeHtml(p.description) + '</td>';
        html += '</tr>';
      });
      html += '</tbody></table><div class="pagination">';
      html += '<button class="btn" onclick="changePage(-1)" ' + (currentPage === 1 ? 'disabled' : '') + '>Previous</button>';
      html += '<span>Page ' + currentPage + ' of ' + totalPages + '</span>';
      html += '<button class="btn" onclick="changePage(1)" ' + (currentPage === totalPages ? 'disabled' : '') + '>Next</button>';
      html += '</div>';
      document.getElementById('access-patterns-container').innerHTML = html;
    }

    function buildSourceTableTable() {
      sourceTableGroups = buildSourceTableGroups();
      document.getElementById('pattern-count').textContent = sourceTableGroups.length;
      const start = (currentPage - 1) * PAGE_SIZE;
      const paginated = sourceTableGroups.slice(start, start + PAGE_SIZE);
      const totalPages = Math.ceil(sourceTableGroups.length / PAGE_SIZE);
      let html = '<table><thead><tr><th>Source Table</th><th>Engines</th><th>Destination Tables</th><th>Patterns</th><th>Convergence</th><th>Operations</th></tr></thead><tbody>';
      paginated.forEach(g => {
        const engines = [...g.engines].map(e => {
          return engineBadge(e, ENGINE_LABELS[e] || e);
        }).join(' ');
        const destTables = [...g.destTables].join(', ');
        const opSummary = {};
        g.patterns.forEach(p => { opSummary[p.operation] = (opSummary[p.operation] || 0) + 1; });
        const operations = Object.entries(opSummary).map(function(entry) { return entry[0] + '(' + entry[1] + ')'; }).join(', ');
        const convergence = g.convergesFrom.size > 0 ? '<span class="badge badge-blue">Merged (' + g.convergesFrom.size + ')</span>' : '—';
        html += '<tr onclick="showSourceTableDetails(\'' + escapeHtml(g.table) + '\')">';
        html += '<td><span class="link">' + escapeHtml(g.table) + '</span></td>';
        html += '<td>' + engines + '</td>';
        html += '<td>' + escapeHtml(destTables) + '</td>';
        html += '<td><span class="badge badge-grey">' + g.patterns.length + '</span></td>';
        html += '<td>' + convergence + '</td>';
        html += '<td style="font-size: 12px;">' + escapeHtml(operations) + '</td>';
        html += '</tr>';
      });
      html += '</tbody></table><div class="pagination">';
      html += '<button class="btn" onclick="changePage(-1)" ' + (currentPage === 1 ? 'disabled' : '') + '>Previous</button>';
      html += '<span>Page ' + currentPage + ' of ' + totalPages + '</span>';
      html += '<button class="btn" onclick="changePage(1)" ' + (currentPage === totalPages ? 'disabled' : '') + '>Next</button>';
      html += '</div>';
      document.getElementById('access-patterns-container').innerHTML = html;
    }

    function changePage(delta) {
      currentPage += delta;
      buildTable();
    }

    function createCharts() {
      const filtered = filterPatterns();
      const engineDist = {}, opDist = {};
      filtered.forEach(p => {
        engineDist[p.engine] = (engineDist[p.engine] || 0) + 1;
        opDist[p.opCategory] = (opDist[p.opCategory] || 0) + 1;
      });
      if (engineChart) engineChart.destroy();
      engineChart = new Chart(document.getElementById('engineChart'), {
        type: 'pie',
        data: {
          labels: Object.keys(engineDist).map(e => ENGINE_LABELS[e] || e),
          datasets: [{ data: Object.values(engineDist), backgroundColor: Object.keys(engineDist).map(e => engineColor(e)) }]
        },
        options: {
          responsive: true, maintainAspectRatio: false,
          onClick: (e, items) => {
            if (items.length > 0) {
              const index = items[0].index;
              const engine = Object.keys(engineDist)[index];
              if (!activeFilters.engines.includes(engine)) {
                activeFilters.engines.push(engine);
                updateFilterDisplay();
                buildTable();
              }
            }
          },
          plugins: { legend: { position: 'bottom' } }
        }
      });
      if (operationChart) operationChart.destroy();
      operationChart = new Chart(document.getElementById('operationChart'), {
        type: 'doughnut',
        data: {
          labels: Object.keys(opDist).map(o => o.charAt(0).toUpperCase() + o.slice(1)),
          datasets: [{ data: Object.values(opDist), backgroundColor: Object.keys(opDist).map(o => opColor(o)) }]
        },
        options: {
          responsive: true, maintainAspectRatio: false,
          onClick: (e, items) => {
            if (items.length > 0) {
              const index = items[0].index;
              const op = Object.keys(opDist)[index];
              if (!activeFilters.operations.includes(op)) {
                activeFilters.operations.push(op);
                updateFilterDisplay();
                buildTable();
              }
            }
          },
          plugins: { legend: { position: 'bottom' } }
        }
      });
    }

    function updateCharts() { createCharts(); }

    function buildCostBreakdown() {
      const container = document.getElementById('cost-breakdown-container');
      const costs = DATA.results?.synthesis?.tco_analysis?.cost_breakdown || [];
      const afterDist = DATA.results?.synthesis?.reality_check?.after_distribution || {};
      const active = costs.filter(cb => afterDist[cb.database]);
      if (active.length === 0) { container.innerHTML = '<p>No cost data available.</p>'; return; }
      let html = '<div class="grid grid-auto">';      active.forEach(cb => {
        html += '<div class="stat-card" style="text-align: center;">';
        html += engineBadge(cb.database, ENGINE_LABELS[cb.database] || cb.database);
        html += '<div style="font-size: 36px; font-weight: 700; margin: 8px 0 0; line-height: 1.15;">$' + (cb.monthly_cost_usd?.toFixed(2) || '0.00') + '</div>';
        html += '<div style="font-size: 13px; color: var(--color-text-secondary);">month · ' + cb.pricing_mode + '</div>';
        html += '</div>';
      });
      html += '</div>';
      container.innerHTML = html;
    }

    function buildQueryFlow() {
      const container = document.getElementById('query-flow-container');
      const afterDist = DATA.results?.synthesis?.reality_check?.after_distribution || {};
      if (Object.keys(afterDist).length === 0) { container.innerHTML = '<p>No query flow data available.</p>'; return; }
      const totalQueries = Object.values(afterDist).reduce((sum, count) => sum + count, 0);
      const sortedEngines = Object.entries(afterDist).sort((a, b) => b[1] - a[1]);
      const svgWidth = 900;
      const engineSpacing = 100;
      const svgHeight = Math.max(300, sortedEngines.length * engineSpacing + 100);
      const nodeWidth = 26;
      const sourceX = 100;
      const targetX = svgWidth - 200;
      const sourceY = svgHeight / 2;
      const totalHeight = sortedEngines.length * engineSpacing;
      const startY = (svgHeight - totalHeight) / 2;
      let html = '<div style="width: 100%; display: flex; justify-content: center; align-items: center;">';
      html += '<svg width="' + svgWidth + '" height="' + svgHeight + '" style="background: transparent;">';
      html += '<defs>';
      html += '<linearGradient id="gradient-queries" x1="0%" y1="0%" x2="100%" y2="0%">';
      html += '<stop offset="0%" style="stop-color:var(--chart-neutral);stop-opacity:0.4" />';
      html += '<stop offset="100%" style="stop-color:var(--chart-neutral);stop-opacity:0.2" />';
      html += '</linearGradient>';
      sortedEngines.forEach(function(entry) {
        const engine = entry[0];
        const color = engineColor(engine);
        html += '<linearGradient id="gradient-' + engine + '" x1="0%" y1="0%" x2="100%" y2="0%">';
        html += '<stop offset="0%" style="stop-color:' + color + ';stop-opacity:0.4" />';
        html += '<stop offset="100%" style="stop-color:' + color + ';stop-opacity:0.2" />';
        html += '</linearGradient>';
      });
      html += '</defs>';
      sortedEngines.forEach(function(entry, idx) {
        const engine = entry[0], count = entry[1];
        const targetY = startY + (idx * engineSpacing) + (engineSpacing / 2);
        const linkHeight = Math.max(8, (count / totalQueries) * 200);
        const sourceTop = sourceY - linkHeight / 2;
        const sourceBottom = sourceY + linkHeight / 2;
        const targetTop = targetY - linkHeight / 2;
        const targetBottom = targetY + linkHeight / 2;
        const midX = (sourceX + nodeWidth + targetX) / 2;
        const pathData = 'M ' + (sourceX + nodeWidth) + ' ' + sourceTop + ' C ' + midX + ' ' + sourceTop + ', ' + midX + ' ' + targetTop + ', ' + targetX + ' ' + targetTop + ' L ' + targetX + ' ' + targetBottom + ' C ' + midX + ' ' + targetBottom + ', ' + midX + ' ' + sourceBottom + ', ' + (sourceX + nodeWidth) + ' ' + sourceBottom + ' Z';
        html += '<path d="' + pathData + '" fill="url(#gradient-' + engine + ')" stroke="none" opacity="0.6" />';
      });
      const sourceHeight = Math.min(150, svgHeight - 100);
      html += '<rect x="' + sourceX + '" y="' + (sourceY - sourceHeight/2) + '" width="' + nodeWidth + '" height="' + sourceHeight + '" style="fill:var(--chart-neutral);stroke:var(--chart-neutral)" rx="2" opacity="0.8" />';
      sortedEngines.forEach(function(entry, idx) {
        const engine = entry[0], count = entry[1];
        const targetY = startY + (idx * engineSpacing) + (engineSpacing / 2);
        const nodeHeight = Math.max(20, (count / totalQueries) * 120);
        const color = engineColor(engine);
        const label = ENGINE_LABELS[engine] || engine;
        html += '<rect x="' + targetX + '" y="' + (targetY - nodeHeight/2) + '" width="' + nodeWidth + '" height="' + nodeHeight + '" fill="' + color + '" stroke="' + color + '" rx="2" opacity="0.8" />';
        html += '<text x="' + (targetX - 10) + '" y="' + targetY + '" dy="0.35em" text-anchor="end" font-size="14" font-weight="600" fill="var(--color-text)">' + label + ' (' + Number(count).toFixed(1) + '%)</text>';
      });
      html += '</svg></div>';
      container.innerHTML = html;
    }

    function tradeoffsByEngine(kind) {
      const out = {};
      DATA.schemaDesigns.forEach(d => {
        const raw = d.content?.trade_offs || [];
        const normalized = raw.map(t => typeof t === 'object' ? t : { description: String(t), impact: '', source_tables: [], target_tables: [], query_ids: [] });
        const wanted = normalized.filter(t => String(t.description || '').startsWith('[PE note]') === (kind === 'pe'));
        if (wanted.length > 0) out[d.target_type] = wanted;
      });
      return out;
    }

    function sqlIdsHtml(queryIds) {
      if (!queryIds || queryIds.length === 0) return '';
      let out = '<div style="margin-top: 8px;"><div style="font-size: 11px; color: var(--color-text-secondary); font-weight: 600; margin-bottom: 4px;">SQL IDs:</div><div>';
      queryIds.forEach(function(qid) {
        out += '<span class="link" onclick="showQueryJourney(\'' + qid + '\')" style="font-family: monospace; font-size: 11px; margin-right: 8px; display: inline-block; padding: 2px 6px; background: var(--color-bg-layout); border-radius: 4px;">' + qid.substring(0, 12) + '...</span>';
      });
      return out + '</div></div>';
    }

    function engineTabBar(engines, byEngine, btnClass, switchFn) {
      let out = '<div style="border-bottom: 2px solid var(--color-border); margin-bottom: 20px;">';
      engines.forEach(function(engine, idx) {
        const activeStyle = idx === 0 ? 'color: var(--color-blue); border-bottom-color: var(--color-blue);' : 'color: var(--color-text-secondary); border-bottom-color: transparent;';
        out += '<button class="' + btnClass + (idx === 0 ? ' active' : '') + '" onclick="' + switchFn + '(&quot;' + engine + '&quot;)" style="padding: 8px 24px; cursor: pointer; border: none; background: none; font-size: 14px; font-weight: 600; ' + activeStyle + ' margin-bottom: -2px;">' + (ENGINE_LABELS[engine] || engine) + ' (' + byEngine[engine].length + ')</button>';
      });
      return out + '</div>';
    }

    function buildTradeoffs() {
      const container = document.getElementById('tradeoffs-container');
      const byEngine = tradeoffsByEngine('decision');
      const engines = Object.keys(byEngine);
      if (engines.length === 0) { container.innerHTML = '<p>No trade-offs available.</p>'; return; }
      let html = engineTabBar(engines, byEngine, 'tradeoff-tab-btn', 'switchTradeoffTab');
      engines.forEach(function(engine, idx) {
        html += '<div id="tradeoff-tab-' + engine + '" class="tradeoff-tab-content" style="display: ' + (idx === 0 ? 'block' : 'none') + ';">';
        byEngine[engine].forEach(function(to) {
          html += '<div class="item-card">';
          html += '<div style="font-size: 13px; font-weight: 700; color: var(--color-text);">' + escapeHtml(to.description) + '</div>';
          if (to.impact) html += '<div style="font-size: 13px; color: var(--color-text-secondary); margin-top: 4px;">' + escapeHtml(to.impact) + '</div>';
          html += sqlIdsHtml(to.query_ids);
          html += '</div>';
        });
        html += '</div>';
      });
      container.innerHTML = html;
    }

    function buildPeNotes() {
      const container = document.getElementById('pe-notes-container');
      if (!container) return;
      const byEngine = tradeoffsByEngine('pe');
      const engines = Object.keys(byEngine);
      if (engines.length === 0) { container.innerHTML = '<p>No engineering notes were raised.</p>'; return; }
      let html = engineTabBar(engines, byEngine, 'pe-tab-btn', 'switchPeNoteTab');
      engines.forEach(function(engine, idx) {
        html += '<div id="pe-tab-' + engine + '" class="pe-tab-content" style="display: ' + (idx === 0 ? 'block' : 'none') + ';">';
        byEngine[engine].forEach(function(note, noteIdx) {
          html += '<div class="item-card">';
          html += '<div style="display: flex; align-items: flex-start; gap: 12px;">';
          html += '<span style="display: inline-block; padding: 2px 8px; background: var(--color-accent); color: white; border-radius: 4px; font-size: 12px; font-weight: 600; min-width: 24px; text-align: center;">' + (noteIdx + 1) + '</span>';
          html += '<div style="flex: 1;"><div style="font-size: 13px;">' + escapeHtml(note.description.replace(/^\[PE note\]\s*/, '')) + '</div>';
          if (note.impact) html += '<div style="font-size: 12px; color: var(--color-text-secondary); margin-top: 4px;">' + escapeHtml(note.impact) + '</div>';
          html += sqlIdsHtml(note.query_ids);
          html += '</div></div></div>';
        });
        html += '</div>';
      });
      container.innerHTML = html;
    }

    function switchEngineTab(btnClass, contentClass, showId) {
      document.querySelectorAll('.' + btnClass).forEach(btn => { btn.style.color = 'var(--color-text-secondary)'; btn.style.borderBottomColor = 'transparent'; });
      event.target.style.color = 'var(--color-blue)';
      event.target.style.borderBottomColor = 'var(--color-blue)';
      document.querySelectorAll('.' + contentClass).forEach(content => content.style.display = 'none');
      document.getElementById(showId).style.display = 'block';
    }

    function switchTradeoffTab(engineId) { switchEngineTab('tradeoff-tab-btn', 'tradeoff-tab-content', 'tradeoff-tab-' + engineId); }

    function switchPeNoteTab(engineId) { switchEngineTab('pe-tab-btn', 'pe-tab-content', 'pe-tab-' + engineId); }

    function showPatternDetails(patternId) {
      const pattern = allPatterns.find(p => p.id === patternId);
      if (!pattern) { alert('Pattern not found: ' + patternId); return; }
      let fullPattern = null;
      DATA.schemaDesigns.forEach(design => {
        const content = design.content || {};
        (content.access_patterns || []).forEach(ap => {
          const id = ap.pattern_id || ap.name || (design.target_type + '-' + ap.operation);
          if (id === patternId) fullPattern = Object.assign({}, ap, { engine: design.target_type });
        });
      });
      if (!fullPattern) fullPattern = pattern;
      let modal = document.getElementById('pattern-modal');
      if (!modal) {
        modal = document.createElement('div');
        modal.id = 'pattern-modal';
        modal.className = 'modal-overlay';
        modal.innerHTML = '<div class="modal-content"><div class="modal-header"><h2 id="pattern-modal-title">Pattern Details</h2><button class="modal-close" onclick="closePatternModal()">×</button></div><div class="modal-body" id="pattern-modal-body"></div></div>';
        document.body.appendChild(modal);
      }
      document.getElementById('pattern-modal-title').textContent = 'Pattern: ' + patternId.slice(0, 12);
      let tabsHtml = '<div class="tab-bar">';
      tabsHtml += '<button class="tab-button active" onclick="switchPatternTab(\'overview\')">Overview</button>';
      tabsHtml += '<button class="tab-button" onclick="switchPatternTab(\'details\')">Details</button>';
      tabsHtml += '<button class="tab-button" onclick="switchPatternTab(\'source\')">Source Query</button>';
      tabsHtml += '<button class="tab-button" onclick="switchPatternTab(\'target\')">Target Pattern</button>';
      tabsHtml += '</div>';
      tabsHtml += '<div id="pattern-tab-overview" class="tab-content active">';
      tabsHtml += '<div style="margin-bottom: 24px;"><div class="key-value-label">Description</div>';
      tabsHtml += '<div class="key-value-value" style="margin-top: 4px; padding: 16px; background: var(--color-bg-layout); border-radius: 8px;">' + escapeHtml(fullPattern.description || fullPattern.name || 'No description available') + '</div></div>';
      tabsHtml += '<div class="key-value-grid">';
      tabsHtml += '<div class="key-value-item"><div class="key-value-label">Engine</div><div class="key-value-value">' + engineBadge(fullPattern.engine, ENGINE_LABELS[fullPattern.engine] || fullPattern.engine) + '</div></div>';
      tabsHtml += '<div class="key-value-item"><div class="key-value-label">Operation</div><div class="key-value-value">' + escapeHtml(fullPattern.operation || fullPattern.http_method || '—') + '</div></div>';
      tabsHtml += '<div class="key-value-item"><div class="key-value-label">Destination Table</div><div class="key-value-value">' + escapeHtml(fullPattern.table_name || fullPattern.key_pattern || fullPattern.index_or_stream || fullPattern.index || fullPattern.collection || '—') + '</div></div>';
      tabsHtml += '</div>';
      if (fullPattern.source_tables && fullPattern.source_tables.length > 0) {
        tabsHtml += '<div class="key-value-block"><div class="key-value-label">Source Tables</div><div>';
        fullPattern.source_tables.forEach(function(t) {
          tabsHtml += '<span class="badge badge-grey">' + t.split('.').pop() + '</span> ';
        });
        tabsHtml += '</div></div>';
      }
      if (fullPattern.query_ids && fullPattern.query_ids.length > 0) {
        tabsHtml += '<div class="key-value-block"><div class="key-value-label">SQL IDs (' + fullPattern.query_ids.length + ')</div><div style="display: flex; flex-wrap: wrap; gap: 8px;">';
        fullPattern.query_ids.forEach(function(qid) {
          const hasJourney = QUERY_JOURNEY_LOOKUP[qid];
          const cursorStyle = hasJourney ? 'cursor: pointer;' : 'opacity: 0.6;';
          const onclickAttr = hasJourney ? ' onclick="showQueryJourney(\'' + qid + '\')"' : '';
          const titleAttr = hasJourney ? 'Click to view query journey' : 'Query journey not available';
          tabsHtml += '<span class="badge badge-blue" style="' + cursorStyle + '" title="' + titleAttr + '"' + onclickAttr + '>' + qid.slice(0, 8) + '...</span>';
        });
        tabsHtml += '</div></div>';
      }
      tabsHtml += '</div>';
      tabsHtml += '<div id="pattern-tab-details" class="tab-content"><div class="key-value-grid">';
      if (fullPattern.gsi_name) tabsHtml += '<div class="key-value-item"><div class="key-value-label">GSI Name</div><div class="key-value-value">' + escapeHtml(fullPattern.gsi_name) + '</div></div>';
      if (fullPattern.partition_key) tabsHtml += '<div class="key-value-item"><div class="key-value-label">Partition Key</div><div class="key-value-value">' + escapeHtml(fullPattern.partition_key) + '</div></div>';
      if (fullPattern.sort_key) tabsHtml += '<div class="key-value-item"><div class="key-value-label">Sort Key</div><div class="key-value-value">' + escapeHtml(fullPattern.sort_key) + '</div></div>';
      if (fullPattern.filter_expression) tabsHtml += '<div class="key-value-item"><div class="key-value-label">Filter Expression</div><div class="key-value-value">' + escapeHtml(fullPattern.filter_expression) + '</div></div>';
      if (fullPattern.projection) tabsHtml += '<div class="key-value-item"><div class="key-value-label">Projection</div><div class="key-value-value">' + escapeHtml(fullPattern.projection) + '</div></div>';
      if (fullPattern.consistency) tabsHtml += '<div class="key-value-item"><div class="key-value-label">Consistency</div><div class="key-value-value">' + escapeHtml(fullPattern.consistency) + '</div></div>';
      if (fullPattern.estimated_rps != null) tabsHtml += '<div class="key-value-item"><div class="key-value-label">Estimated RPS</div><div class="key-value-value">' + fullPattern.estimated_rps + '</div></div>';
      if (fullPattern.estimated_item_size != null) tabsHtml += '<div class="key-value-item"><div class="key-value-label">Estimated Item Size</div><div class="key-value-value">' + fullPattern.estimated_item_size + ' bytes</div></div>';
      tabsHtml += '</div></div>';
      tabsHtml += '<div id="pattern-tab-source" class="tab-content">';
      if (fullPattern.source_query) {
        tabsHtml += '<div><div class="key-value-label">Source SQL Query</div><div class="code-block">' + escapeHtml(fullPattern.source_query) + '</div></div>';
      } else {
        tabsHtml += '<p style="color: var(--color-text-secondary);">No source query available for this pattern.</p>';
      }
      tabsHtml += '</div>';
      tabsHtml += '<div id="pattern-tab-target" class="tab-content">';
      if (fullPattern.key_condition) tabsHtml += '<div><div class="key-value-label">Key Condition Expression</div><div class="code-block">' + escapeHtml(fullPattern.key_condition) + '</div></div>';
      if (fullPattern.dsl_query) {
        tabsHtml += '<div class="key-value-block"><div class="key-value-label">OpenSearch DSL Query</div><div class="code-block">' + (typeof fullPattern.dsl_query === 'string' ? escapeHtml(fullPattern.dsl_query) : JSON.stringify(fullPattern.dsl_query, null, 2)) + '</div></div>';
      }
      if (!fullPattern.key_condition && !fullPattern.dsl_query) tabsHtml += '<p style="color: var(--color-text-secondary);">No target pattern details available.</p>';
      tabsHtml += '</div>';
      document.getElementById('pattern-modal-body').innerHTML = tabsHtml;
      modal.style.display = 'flex';
    }

    function closePatternModal() {
      const modal = document.getElementById('pattern-modal');
      if (modal) modal.style.display = 'none';
    }

    function switchPatternTab(tabName) {
      document.querySelectorAll('#pattern-modal .tab-button').forEach(btn => btn.classList.remove('active'));
      event.target.classList.add('active');
      document.querySelectorAll('#pattern-modal .tab-content').forEach(content => content.classList.remove('active'));
      document.getElementById('pattern-tab-' + tabName).classList.add('active');
    }

    function showSourceTableDetails(tableName) {
      const group = sourceTableGroups.find(g => g.table === tableName);
      if (!group) { alert('Source table not found: ' + tableName); return; }
      let modal = document.getElementById('source-table-modal');
      if (!modal) {
        modal = document.createElement('div');
        modal.id = 'source-table-modal';
        modal.className = 'modal-overlay';
        modal.innerHTML = '<div class="modal-content"><div class="modal-header"><h2 id="source-table-modal-title">Source Table Details</h2><button class="modal-close" onclick="closeSourceTableModal()">×</button></div><div class="modal-body" id="source-table-modal-body"></div></div>';
        document.body.appendChild(modal);
      }
      document.getElementById('source-table-modal-title').textContent = 'Source Table: ' + tableName;
      const byEngine = {};
      group.patterns.forEach(ap => {
        if (!byEngine[ap.engine]) byEngine[ap.engine] = [];
        byEngine[ap.engine].push(ap);
      });
      let tabsHtml = '<div class="tab-bar">';
      Object.keys(byEngine).forEach(function(engine, idx) {
        const activeClass = idx === 0 ? ' active' : '';
        tabsHtml += '<button class="tab-button' + activeClass + '" onclick="switchSourceTableTab(\'' + engine + '\')">';
        tabsHtml += (ENGINE_LABELS[engine] || engine) + ' (' + byEngine[engine].length + ')';
        tabsHtml += '</button>';
      });
      tabsHtml += '</div>';
      Object.entries(byEngine).forEach(function(entry, idx) {
        const engine = entry[0], patterns = entry[1];
        const byDest = {};
        patterns.forEach(ap => {
          const key = ap.destTable;
          if (!byDest[key]) byDest[key] = [];
          byDest[key].push(ap);
        });
        const badgeClass = ENGINE_BADGE_CLASSES[engine] || 'badge-grey';
        const displayStyle = idx === 0 ? 'block' : 'none';
        const activeClass = idx === 0 ? ' active' : '';
        tabsHtml += '<div id="source-table-tab-' + engine + '" class="tab-content' + activeClass + '" style="display: ' + displayStyle + ';">';
        tabsHtml += '<div style="margin-bottom: 16px;"><div class="key-value-grid">';
        tabsHtml += '<div class="key-value-item"><div class="key-value-label">Source Table</div><div class="key-value-value">' + escapeHtml(tableName) + '</div></div>';
        tabsHtml += '<div class="key-value-item"><div class="key-value-label">Target Engine</div><div class="key-value-value">' + engineBadge(engine, ENGINE_LABELS[engine] || engine) + '</div></div>';
        tabsHtml += '<div class="key-value-item"><div class="key-value-label">Total Patterns</div><div class="key-value-value"><span class="badge badge-grey">' + patterns.length + '</span></div></div>';
        tabsHtml += '</div></div>';
        Object.entries(byDest).forEach(function(destEntry) {
          const destTable = destEntry[0], destPatterns = destEntry[1];
          tabsHtml += '<div style="margin-bottom: 24px; padding: 20px; background: var(--color-bg-layout); border-radius: 8px;">';
          tabsHtml += '<div class="key-value-label">Destination: ' + escapeHtml(destTable) + '</div>';
          tabsHtml += '<div style="color: var(--color-text-secondary); margin-bottom: 8px;">' + destPatterns.length + ' pattern(s)</div>';
          tabsHtml += '<table><thead><tr>';
          tabsHtml += '<th style="text-align: left; padding: 4px 8px;">Pattern ID</th>';
          tabsHtml += '<th style="text-align: left; padding: 4px 8px;">Operation</th>';
          tabsHtml += '<th style="text-align: left; padding: 4px 8px;">Description</th>';
          tabsHtml += '</tr></thead><tbody>';
          destPatterns.forEach(function(p) {
            tabsHtml += '<tr onclick="closeSourceTableModal(); showPatternDetails(\'' + escapeHtml(p.id) + '\');" style="cursor: pointer;">';
            tabsHtml += '<td style="padding: 4px 8px;"><span class="link">' + escapeHtml(p.id.slice(0, 12)) + '</span></td>';
            tabsHtml += '<td style="padding: 4px 8px;">' + escapeHtml(p.operation) + '</td>';
            tabsHtml += '<td style="padding: 4px 8px;">' + escapeHtml(p.description) + '</td>';
            tabsHtml += '</tr>';
          });
          tabsHtml += '</tbody></table></div>';
        });
        tabsHtml += '</div>';
      });
      document.getElementById('source-table-modal-body').innerHTML = tabsHtml;
      modal.style.display = 'flex';
    }

    function closeSourceTableModal() {
      const modal = document.getElementById('source-table-modal');
      if (modal) modal.style.display = 'none';
    }

    function switchSourceTableTab(engineId) {
      document.querySelectorAll('#source-table-modal .tab-button').forEach(btn => btn.classList.remove('active'));
      event.target.classList.add('active');
      document.querySelectorAll('#source-table-modal .tab-content').forEach(content => content.classList.remove('active'));
      document.getElementById('source-table-tab-' + engineId).classList.add('active');
    }

    function showQueryJourney(queryId) {
      const journey = QUERY_JOURNEY_LOOKUP[queryId];
      if (!journey) {
        alert('Query journey data not found for: ' + queryId + '\n\nAvailable query IDs: ' + Object.keys(QUERY_JOURNEY_LOOKUP).length);
        console.log('QUERY_JOURNEY_LOOKUP:', QUERY_JOURNEY_LOOKUP);
        console.log('Requested queryId:', queryId);
        return;
      }
      let modal = document.getElementById('query-journey-modal');
      if (!modal) {
        modal = document.createElement('div');
        modal.id = 'query-journey-modal';
        modal.style.cssText = 'display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.5); z-index: 1000; align-items: center; justify-content: center;';
        modal.innerHTML = '<div class="modal-content"><div class="modal-header"><h2 id="query-modal-title">Query Journey</h2><button class="modal-close" onclick="closeQueryJourneyModal()">×</button></div><div class="modal-body" id="query-modal-body"></div></div>';
        document.body.appendChild(modal);
      }
      document.getElementById('query-modal-title').textContent = 'Query Journey: ' + queryId.substring(0, 16) + '...';
      const source = journey.source || {};
      const assignment = journey.assignment || {};
      const performance = source.performance || {};
      const characteristics = source.characteristics || {};
      let tabsHtml = '<div style="border-bottom: 2px solid var(--color-border); margin-bottom: 16px;">';
      tabsHtml += '<button class="tab-btn active" onclick="switchQueryTab(\'general\')" style="padding: 8px 24px; cursor: pointer; border: none; background: none; font-size: 14px; font-weight: 600; color: var(--color-blue); border-bottom: 2px solid var(--color-blue); margin-bottom: -2px;">General Information</button>';
      tabsHtml += '<button class="tab-btn" onclick="switchQueryTab(\'performance\')" style="padding: 8px 24px; cursor: pointer; border: none; background: none; font-size: 14px; font-weight: 600; color: var(--color-text-secondary); border-bottom: 2px solid transparent; margin-bottom: -2px;">Performance</button>';
      tabsHtml += '<button class="tab-btn" onclick="switchQueryTab(\'characteristics\')" style="padding: 8px 24px; cursor: pointer; border: none; background: none; font-size: 14px; font-weight: 600; color: var(--color-text-secondary); border-bottom: 2px solid transparent; margin-bottom: -2px;">Characteristics</button>';
      tabsHtml += '<button class="tab-btn" onclick="switchQueryTab(\'json\')" style="padding: 8px 24px; cursor: pointer; border: none; background: none; font-size: 14px; font-weight: 600; color: var(--color-text-secondary); border-bottom: 2px solid transparent; margin-bottom: -2px;">JSON</button>';
      tabsHtml += '</div>';
      tabsHtml += '<div id="tab-general" class="tab-content" style="display: block;">';
      tabsHtml += '<div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; margin-bottom: 16px;">';
      tabsHtml += '<div><div class="key-value-label">Query Type</div><div>' + escapeHtml(source.query_type || '—') + '</div></div>';
      tabsHtml += '<div><div class="key-value-label">Assigned Engine</div><div><span class="badge badge-blue">' + escapeHtml(assignment.assigned_engine || '—') + '</span></div></div>';
      tabsHtml += '<div><div class="key-value-label">Confidence</div><div>' + (assignment.confidence || '—') + '%</div></div>';
      tabsHtml += '<div><div class="key-value-label">Frequency (per hour)</div><div>' + (source.frequency_per_hour ? source.frequency_per_hour.toFixed(2) : '—') + '</div></div>';
      tabsHtml += '<div><div class="key-value-label">Calls per Second</div><div>' + (source.calls_per_second ? source.calls_per_second.toFixed(4) : '—') + '</div></div>';
      tabsHtml += '<div><div class="key-value-label">In Scope</div><div>' + (assignment.in_scope ? 'Yes' : 'No') + '</div></div>';
      tabsHtml += '</div>';
      if (source.tables_accessed && source.tables_accessed.length > 0) {
        tabsHtml += '<div class="key-value-block"><div class="key-value-label">Tables Accessed</div><div>';
        source.tables_accessed.forEach(function(t) { tabsHtml += '<span class="badge badge-grey">' + escapeHtml(t) + '</span> '; });
        tabsHtml += '</div></div>';
      }
      if (source.query_text) {
        tabsHtml += '<div class="key-value-block"><div class="key-value-label">Query Text</div>';
        tabsHtml += '<div class="code-block">' + escapeHtml(source.query_text) + '</div></div>';
      }
      tabsHtml += '</div>';
      tabsHtml += '<div id="tab-performance" class="tab-content" style="display: none;">';
      if (Object.keys(performance).length > 0) {
        tabsHtml += '<div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px;">';
        Object.entries(performance).forEach(function(entry) {
          const key = entry[0], value = entry[1];
          const label = key.replace(/_/g, ' ').replace(/\b\w/g, function(l) { return l.toUpperCase(); });
          const displayValue = value !== null && value !== undefined ? (typeof value === 'number' ? value.toFixed(4) : escapeHtml(String(value))) : '—';
          tabsHtml += '<div><div class="key-value-label">' + escapeHtml(label) + '</div><div>' + displayValue + '</div></div>';
        });
        tabsHtml += '</div>';
      } else {
        tabsHtml += '<p style="color: var(--color-text-secondary);">No performance data available</p>';
      }
      tabsHtml += '</div>';
      tabsHtml += '<div id="tab-characteristics" class="tab-content" style="display: none;">';
      if (Object.keys(characteristics).length > 0) {
        tabsHtml += '<div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px;">';
        Object.entries(characteristics).forEach(function(entry) {
          const key = entry[0], value = entry[1];
          const label = key.replace(/_/g, ' ').replace(/\b\w/g, function(l) { return l.toUpperCase(); });
          const displayValue = value !== null && value !== undefined ? escapeHtml(String(value)) : '—';
          tabsHtml += '<div><div class="key-value-label">' + escapeHtml(label) + '</div><div>' + displayValue + '</div></div>';
        });
        tabsHtml += '</div>';
      } else {
        tabsHtml += '<p style="color: var(--color-text-secondary);">No characteristics data available</p>';
      }
      tabsHtml += '</div>';
      tabsHtml += '<div id="tab-json" class="tab-content" style="display: none;">';
      tabsHtml += '<div class="code-block" style="white-space: pre;">' + JSON.stringify(journey, null, 2) + '</div>';
      tabsHtml += '</div>';
      document.getElementById('query-modal-body').innerHTML = tabsHtml;
      modal.style.display = 'flex';
    }

    function closeQueryJourneyModal() {
      const modal = document.getElementById('query-journey-modal');
      if (modal) modal.style.display = 'none';
    }

    function switchQueryTab(tabName) {
      document.querySelectorAll('.tab-btn').forEach(btn => { btn.style.color = 'var(--color-text-secondary)'; btn.style.borderBottomColor = 'transparent'; });
      event.target.style.color = 'var(--color-blue)';
      event.target.style.borderBottomColor = 'var(--color-blue)';
      document.querySelectorAll('.tab-content').forEach(content => content.style.display = 'none');
      document.getElementById('tab-' + tabName).style.display = 'block';
    }

    window.addEventListener('click', (event) => {
      const queryModal = document.getElementById('query-journey-modal');
      if (queryModal && event.target === queryModal) closeQueryJourneyModal();
      const patternModal = document.getElementById('pattern-modal');
      if (patternModal && event.target === patternModal) closePatternModal();
      const sourceTableModal = document.getElementById('source-table-modal');
      if (sourceTableModal && event.target === sourceTableModal) closeSourceTableModal();
    });

    document.getElementById('filter-input').addEventListener('input', (e) => {
      activeFilters.text = e.target.value;
      currentPage = 1;
      buildTable();
    });

    document.addEventListener('DOMContentLoaded', () => {
      allPatterns = extractPatterns();
      buildCostBreakdown();
      buildQueryFlow();
      buildTable();
      createCharts();
      buildTradeoffs();
      buildPeNotes();
    });
