"""``src/ui/src/utils/engineNames.js`` must match ``ENGINE_DISPLAY_NAMES`` (#225).

``engineNames.js`` is a hand-kept JS copy of the Python engine display-name
map (not generated by ``scripts/sync_report_template.py``, which only lifts
``ExportReport.js``'s own copy into the ATX renderer's templates). This test
parses the JS object literal and compares it against the Python source of
truth, so a copy left behind by an engine-name edit fails CI instead of
silently drifting.
"""

from __future__ import annotations

import re
from pathlib import Path

from src.shared.engine_names import ENGINE_DISPLAY_NAMES

JS_PATH = Path(__file__).resolve().parents[3] / "src" / "ui" / "src" / "utils" / "engineNames.js"

_ENTRY_RE = re.compile(r"""^\s*(\w+):\s*'([^']*)',?\s*$""")


def _parse_engine_labels(js_text: str) -> dict[str, str]:
    start = js_text.index("ENGINE_LABELS = {")
    end = js_text.index("};", start)
    body = js_text[start:end]
    labels: dict[str, str] = {}
    for line in body.splitlines():
        m = _ENTRY_RE.match(line)
        if m:
            labels[m.group(1)] = m.group(2)
    return labels


class TestEngineNamesJsMatchesPython:
    def test_js_labels_match_engine_display_names(self):
        js_text = JS_PATH.read_text(encoding="utf-8")
        js_labels = _parse_engine_labels(js_text)
        assert js_labels, "failed to parse any ENGINE_LABELS entries from engineNames.js"
        assert js_labels == ENGINE_DISPLAY_NAMES

    def test_extraction_sees_the_known_engines(self):
        # A regression guard on the parser itself: if this starts failing, the
        # regex above stopped matching the file's actual formatting.
        js_text = JS_PATH.read_text(encoding="utf-8")
        js_labels = _parse_engine_labels(js_text)
        assert js_labels["dynamodb"] == "DynamoDB"
        assert js_labels["aurora_mysql"] == "Aurora MySQL"
